routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\UnifiedLoginController;
use App\Http\Controllers\BultinController;
use App\Http\Controllers\Departments\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LeaveController;
use App\Http\Controllers\LettreController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\Positions\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StatistiqueController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;



Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['web.auth'])->prefix('espace-admin')->group(function () {
    // Departments 
    Route::resource('departments', DepartmentController::class);

    // Positions
    Route::resource('positions', PositionController::class);
    Route::get('/positions-by-department/{department}', [PositionController::class, 'getByDepartment'])->name('positions.by.department');
    Route::get('/positions-department/{department}', [PositionController::class, 'getPositionByDepartment'])->name('positionsBydepartment');
    // Employees
    Route::resource('employees', EmployeeController::class);
    Route::get('/contrats/cdi/{id}', [EmployeeController::class, 'downloadCDIContract'])->name('contracts.cdi');
    Route::get('/contrats/cdd/{id}', [EmployeeController::class, 'downloadCDDContract'])->name('contracts.cdd');
    

    // Congés
    Route::resource('leaves', LeaveController::class);
    Route::get('notifications/{id}/read', [LeaveController::class, 'redirectToLeave'])->name('notification.read');
    Route::get('MarkAsRead_all',[LeaveController::class,'MarkAsRead_all'])->name('MarkAsRead_all');
    // Présences
    Route::resource('attendances', AttendanceController::class);
    Route::get('list_attendances', [AttendanceController::class, 'list'])->name('attendances.list');
    Route::get('edit_attendance', [AttendanceController::class,'editAttendance'])->name('attendances.editAttendance');
    Route::get('/pointages/download-pdf', [AttendanceController::class, 'downloadPDF'])->name('attendances.downloadPDF');



    // Paiements
    Route::resource('payments', PaymentController::class);
    Route::get('Details', [PaymentController::class, 'details'])->name('payments.Details');
    Route::get('/paiements/download-pdf', [PaymentController::class, 'downloadPDF'])->name('payments.downloadPDF');
    Route::post('paiements/mass-store', [PaymentController::class, 'massStore'])->name('payments.mass_store');



    // Bulletins
    Route::get('/GenererBulltin', [BultinController::class, 'index'])->name('bulletin.generate');
    Route::post('/showBultinEmploye', [BultinController::class, 'showBulletin'])->name('bulltin.show');
    Route::post('/showBultinPatron', [BultinController::class, 'showBultinPatron'])->name('bulltin.showPatron');

    // Factures
    Route::resource('invoices', InvoiceController::class);
    Route::get('/invoice/{id}/print', [InvoiceController::class, 'print'])->name('invoices.print');
    Route::get('/factures/{invoice}/pdf', [InvoiceController::class, 'downloadInvoice'])->name('invoices.download');


    // Lettres
    Route::get('/lettre/create', [LettreController::class, 'createLettre'])->name('lettre.create');
    Route::get('/lettre/imprimer', [LettreController::class, 'imprimer'])->name('lettre.imprimer');

    Route::get('/Statistique',[StatistiqueController::class,'index'])->name('dashboard.statistique');

    Route::get('/test',function(){
        return view('pages.TestLivewire');
    });
});




// Auth::routes();

Route::get('login', [UnifiedLoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [UnifiedLoginController::class, 'login'])->name('login');
Route::post('logout', [UnifiedLoginController::class, 'logout'])->name('logout');

// Routes pour les utilisateurs généraux (users)
Route::prefix('user')->group(function () {
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
});

Route::group(['middleware' => ['auth']],function(){

    Route::resource('roles',RoleController::class);
    Route::resource('users',UserController::class);

});


 // Groupe de routes pour l'espace employé
 Route::middleware(['auth:employee'])->prefix('espace-employee')->name('employee.')->group(function () {
    Route::get('/info', [EmployeeController::class, 'getInfoEmploiyeeById'])->name('info');
    Route::get('/espaceEmpShow/{employee}', [EmployeeController::class, 'showEmp'])->name('show');
    Route::post('/espaceEmp/{employee}/validate', [EmployeeController::class, 'validateCode'])->name('validate');
    Route::put('EspaceEmpUpdate/{employee}', [EmployeeController::class, 'EspaceEmpUpdate'])->name('EspaceEmpUpdate');
    Route::get('/contratsEmp/cdi/{id}', [EmployeeController::class, 'downloadCDIContractEmployeeAuth'])->name('contracts.cdi');

    Route::get('/contratsEmp/cdd/{id}', [EmployeeController::class, 'downloadCDDContractEmployeeAuth'])->name('contracts.cdd');

    Route::get('/paiements-details', [PaymentController::class, 'getInfoEmploiyeedetailsById'])->name('paiements.details');
    Route::get('/conges', [LeaveController::class, 'getInfoCongesEmploiyeeById'])->name('conges');
    Route::post('/conges/store', [LeaveController::class, 'storeCongesEmploiyeeById'])->name('conges.store');
    Route::post('/conges/annuler', [LeaveController::class, 'AnnulerCongesEmploiyeeById'])->name('conges.annuler');
    Route::get('/bultin', [BultinController::class, 'getInfoEmploiyeeBulletinById'])->name('bultin');
    Route::post('/imprimer-bultin', [BultinController::class, 'ImprimerBultinEmployeeAuth'])->name('bultin.imprimer');
    Route::get('/pointages', [AttendanceController::class, 'getInfoPointagesEmploiyeeById'])->name('pointages');

    

    Route::get('/Dashboard',function(){
        return view('pages.site.dashboard');
    })->name('dashboard');
});

    



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/partial/site/footer-scripts.blade.php
 <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
 <script src="{{ asset('assets/js/libs/jquery-3.1.1.min.js') }}"></script>
 <script src="{{ asset('assets/js/jqueryRepeater.js') }}"></script>
 <script src="{{ asset('bootstrap/js/popper.min.js') }}"></script>
 <script src="{{ asset('bootstrap/js/bootstrap.min.js') }}"></script>
 <script src="{{ asset('plugins/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>
 <script src="{{ asset('assets/js/app.js') }}"></script>
<script src="{{ asset('assets/js/loader.js') }}"></script>

 <script>
     $(document).ready(function() {
         App.init();
     });
 </script>

 <!-- END GLOBAL MANDATORY SCRIPTS -->
 <script src="{{ asset('plugins/table/datatable/datatables.js') }}"></script>


 <script src="{{ asset('assets/js/custom.js') }}"></script>
 <!-- END GLOBAL MANDATORY SCRIPTS -->

 <!-- BEGIN PAGE LEVEL SCRIPTS -->
 <script src="{{ asset('plugins/select2/select2.min.js') }}"></script>
 <script src="{{ asset('assets/js/components/ui-accordions.js') }}"></script>
 <script src="{{ asset('plugins/select2/custom-select2.js') }}"></script>
 <!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM SCRIPTS -->
 <script src="{{ asset('plugins/apex/apexcharts.min.js') }}"></script>
 <script src="{{ asset('assets/js/dashboard/dash_1.js') }}"></script>

resources/views/partial/site/footer.blade.php
<div class="footer-wrapper">
    <div class="footer-section f-section-1">
        <p class="">Copyright © 2024 <a target="_blank" href="https://gitlab.com/users/mowloudfr068/projects">EGTT PFE</a>, Tous le droit sont reserver.</p>
    </div>
    <div class="footer-section f-section-2">
        <p class="">Coded with ISCAE <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                stroke-linejoin="round" class="feather feather-heart">
                <path
                    d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                </path>
            </svg></p>
    </div>
</div>

resources/views/partial/site/head.blade.php
<title>@yield('title')</title>

<link rel="icon" type="image/x-icon" href="{{ asset('assets/img/favicon.ico') }}" />
<link href="{{ asset('assets/cssltr/loader.css') }}" rel="stylesheet"
    type="text/css" />
    <link rel="stylesheet" href="{{ asset('assets/css/wizard.css') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
<link href="{{ asset('bootstrap/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/cssltr/plugins.css') }}"
    rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/table/datatable/datatables.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/select2/select2.min.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/table/datatable/dt-global_style.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/table/datatable/custom_dt_multiple_tables.css') }}">
<link
    href="{{ asset('/assets/cssltr/components/tabs-accordian/custom-accordions.css') }}"
    rel="stylesheet" type="text/css" />

<!-- END GLOBAL MANDATORY STYLES -->
{{-- @yield('css') --}}
<!-- BEGIN PAGE LEVEL PLUGINS/CUSTOM STYLES -->
<link href="{{ asset('plugins/apex/apexcharts.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/cssltr/dashboard/dash_1.css') }}"
    rel="stylesheet" type="text/css" />
<!-- END PAGE LEVEL PLUGINS/CUSTOM STYLES -->

resources/views/partial/site/header.blade.php
<!-- BEGIN LOADER -->
<div id="load_screen">
    <div class="loader">
        <div class="loader-content">
            <div class="spinner-grow align-self-center"></div>
        </div>
    </div>
</div>
<!--  END LOADER -->

<!--  BEGIN NAVBAR  -->
<div class="header-container fixed-top">
    <header class="header navbar navbar-expand-sm">
        <a href="javascript:void(0);" class="sidebarCollapse" data-placement="bottom"><svg
                xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-menu">
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
            </svg></a>
        <ul class="navbar-item flex-row search-ul">
            <li class="nav-item align-self-center search-animated">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather feather-search toggle-search">
                    <circle cx="11" cy="11" r="8"></circle>
                    <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
                </svg>
                <form class="form-inline search-full form-inline search" role="search">
                    <div class="search-bar">
                        <input type="text" class="form-control search-form-control  ml-lg-auto"
                            placeholder="Search...">
                    </div>
                </form>
            </li>
        </ul>
        <ul class="navbar-item flex-row navbar-dropdown">
            <li class="nav-item dropdown user-profile-dropdown  order-lg-0 order-1">
                <a href="javascript:void(0);" class="nav-link dropdown-toggle user" id="userProfileDropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @if (Auth::guard('employee')->user()->photo)
                    <img src="{{ asset('storage/' . Auth::guard('employee')->user()->photo) }}" alt="Photo de Profil" class="img-fluid mr-2">
                        
                    @else
           
                        <img src="{{ asset('images/logo_user.png') }}" alt="Photo de Profil" class="img-fluid mr-2">
                  
                    @endif
                </a>
                <div class="dropdown-menu position-absolute" aria-labelledby="userProfileDropdown">
                    <div class="user-profile-section">
                        <div class="media mx-auto">
                            @if (Auth::guard('employee')->user()->photo)
                                
                            <img src="{{ asset('storage/' . Auth::guard('employee')->user()->photo) }}" alt="Photo de Profil" class="img-fluid mr-2">
                            @else
                            <img src="{{ asset('images/logo_user.png') }}" alt="Photo de Profil" class="img-fluid mr-2">
                            @endif
                            <div class="media-body">
                                <h5>
                                    {{ Auth::guard('employee')->user()->first_name }}
                               
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown-item">
                        <a href="{{ route('employee.info') }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
                                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                                <circle cx="12" cy="7" r="4"></circle>
                            </svg> <span> Profil</span>
                        </a>
                    </div>
                    <div class="dropdown-item">
                        
                        <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                stroke-linecap="round" stroke-linejoin="round" class="feather feather-log-out">
                                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                <polyline points="16 17 21 12 16 7"></polyline>
                                <line x1="21" y1="12" x2="9" y2="12"></line>
                            </svg>
                            <span>Déconnexion</span>
                        </a>
                        
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                        
                    </div>
                </div>
            </li>
        </ul>
    </header>
</div>

<!--  END NAVBAR  -->

resources/views/partial/site/sidebar.blade.php
<style>
    .sidebar-wrapper .menu {
    margin-bottom: 15px; /* Ajoute un espacement vertical entre les menus */
}

.sidebar-wrapper .menu a {
    padding: 10px 15px; /* Augmente la taille du padding pour un espacement intérieur plus confortable */
    border-radius: 5px; /* Ajoute un léger arrondi pour un design plus moderne */
    transition: background-color 0.3s ease; /* Ajoute une transition pour un effet visuel fluide */
}

.sidebar-wrapper .menu a:hover {
    background-color: #f4f4f4; /* Change le fond au survol */
}

</style>
<div class="sidebar-wrapper sidebar-theme">
    <nav id="sidebar">
        <ul class="navbar-nav theme-brand flex-row text-center">
            <li class="nav-item theme-text">
                <a href="index.html" class="nav-link">Espace Employés</a>
            </li>
            <li class="nav-item toggle-sidebar">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                    stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                    class="feather sidebarCollapse feather-chevrons-left">
                    <polyline points="11 17 6 12 11 7"></polyline>
                    <polyline points="18 17 13 12 18 7"></polyline>
                </svg>
            </li>
        </ul>
        <div class="shadow-bottom"></div>
        <ul class="list-unstyled menu-categories" id="accordionExample">
            <li class="menu active">
                <a href="#dashboard" data-toggle="collapse" aria-expanded="true" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="feather feather-home">
                            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                            <polyline points="9 22 9 12 15 12 15 22"></polyline>
                        </svg>
                        <span>{{ __('Tableau De Bord') }}</span>
                    </div>
                </a>
            </li>
            <li class="menu">
                <a href="#info" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor"
    stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
    <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
    <circle cx="12" cy="7" r="4"></circle>
</svg>

                        <span>{{ __('Profil') }}</span>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="info" data-parent="#accordionExample">
                    <li>
                        <a href="{{ route('employee.info') }}">{{ __('Voir mes informations') }}</a>
                    </li>
                </ul>
            </li>
            <li class="menu">
                <a href="#conges" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar">
                            <rect x="3" y="4" width="18" height="16" rx="2" ry="2"></rect>
                            <line x1="16" y1="2" x2="16" y2="6"></line>
                            <line x1="8" y1="2" x2="8" y2="6"></line>
                            <line x1="3" y1="10" x2="21" y2="10"></line>
                          </svg>
                          
                        <span>{{ __('Congés') }}</span>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="conges" data-parent="#accordionExample">
                    <li>
                        <a href="{{ route('employee.conges') }}">{{ __('Demander un congé') }}</a>
                    </li>
                </ul>
            </li>
            <li class="menu">
                <a href="#pointages" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock">
                            <circle cx="12" cy="12" r="10"></circle>
                            <line x1="12" y1="6" x2="12" y2="12"></line>
                            <line x1="12" y1="12" x2="16" y2="10"></line>
                          </svg>
                          
                        <span>{{ __('Pointages') }}</span>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="pointages" data-parent="#accordionExample">
                    <li>
                        <a href="{{ route('employee.pointages') }}">{{ __('Voir mes pointages') }}</a>
                    </li>
                </ul>
            </li>
            <li class="menu">
                <a href="#payments" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-credit-card">
                            <rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect>
                            <line x1="1" y1="10" x2="23" y2="10"></line>
                          </svg>
                          
                          
                          
                        <span>{{ __('Paiements') }}</span>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="payments" data-parent="#accordionExample">
                    <li>
                        <a href="{{ route('employee.paiements.details') }}">{{ __('Voir mes détails des paiements') }}</a>
                    </li>
                </ul>
            </li>
            <li class="menu">
                <a href="#bultin" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                    <div class="">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6z"></path>
                            <line x1="14" y1="2" x2="14" y2="8"></line>
                            <line x1="6" y1="10" x2="18" y2="10"></line>
                            <line x1="6" y1="14" x2="18" y2="14"></line>
                            <line x1="6" y1="18" x2="18" y2="18"></line>
                          </svg>
                          
                        <span>{{ __('Bulletins') }}</span>
                    </div>
                </a>
                <ul class="collapse submenu list-unstyled" id="bultin" data-parent="#accordionExample">
                    <li>
                        <a href="{{ route('employee.bultin') }}">{{ __('Voir bulletin de salaire') }}</a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</div>