routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\UnifiedLoginController;
use App\Http\Controllers\BultinController;
use App\Http\Controllers\Departments\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LeaveController;
use App\Http\Controllers\LettreController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\Positions\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StatistiqueController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;



Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['web.auth'])->prefix('espace-admin')->group(function () {
    // Departments 
    Route::resource('departments', DepartmentController::class);

    // Positions
    Route::resource('positions', PositionController::class);
    Route::get('/positions-by-department/{department}', [PositionController::class, 'getByDepartment'])->name('positions.by.department');
    Route::get('/positions-department/{department}', [PositionController::class, 'getPositionByDepartment'])->name('positionsBydepartment');
    // Employees
    Route::resource('employees', EmployeeController::class);
    Route::get('/contrats/cdi/{id}', [EmployeeController::class, 'downloadCDIContract'])->name('contracts.cdi');
    Route::get('/contrats/cdd/{id}', [EmployeeController::class, 'downloadCDDContract'])->name('contracts.cdd');
    

    // Congés
    Route::resource('leaves', LeaveController::class);
    Route::get('notifications/{id}/read', [LeaveController::class, 'redirectToLeave'])->name('notification.read');
    Route::get('MarkAsRead_all',[LeaveController::class,'MarkAsRead_all'])->name('MarkAsRead_all');
    // Présences
    Route::resource('attendances', AttendanceController::class);
    Route::get('list_attendances', [AttendanceController::class, 'list'])->name('attendances.list');
    Route::get('edit_attendance', [AttendanceController::class,'editAttendance'])->name('attendances.editAttendance');
    Route::get('/pointages/download-pdf', [AttendanceController::class, 'downloadPDF'])->name('attendances.downloadPDF');



    // Paiements
    Route::resource('payments', PaymentController::class);
    Route::get('Details', [PaymentController::class, 'details'])->name('payments.Details');
    Route::get('/paiements/download-pdf', [PaymentController::class, 'downloadPDF'])->name('payments.downloadPDF');
    Route::post('paiements/mass-store', [PaymentController::class, 'massStore'])->name('payments.mass_store');



    // Bulletins
    Route::get('/GenererBulltin', [BultinController::class, 'index'])->name('bulletin.generate');
    Route::post('/showBultinEmploye', [BultinController::class, 'showBulletin'])->name('bulltin.show');
    Route::post('/showBultinPatron', [BultinController::class, 'showBultinPatron'])->name('bulltin.showPatron');

    // Factures
    Route::resource('invoices', InvoiceController::class);
    Route::get('/invoice/{id}/print', [InvoiceController::class, 'print'])->name('invoices.print');
    Route::get('/factures/{invoice}/pdf', [InvoiceController::class, 'downloadInvoice'])->name('invoices.download');


    // Lettres
    Route::get('/lettre/create', [LettreController::class, 'createLettre'])->name('lettre.create');
    Route::get('/lettre/imprimer', [LettreController::class, 'imprimer'])->name('lettre.imprimer');

    Route::get('/Statistique',[StatistiqueController::class,'index'])->name('dashboard.statistique');

    Route::get('/test',function(){
        return view('pages.TestLivewire');
    });
});




// Auth::routes();

Route::get('login', [UnifiedLoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [UnifiedLoginController::class, 'login'])->name('login');
Route::post('logout', [UnifiedLoginController::class, 'logout'])->name('logout');

// Routes pour les utilisateurs généraux (users)
Route::prefix('user')->group(function () {
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
});

Route::group(['middleware' => ['auth']],function(){

    Route::resource('roles',RoleController::class);
    Route::resource('users',UserController::class);

});


 // Groupe de routes pour l'espace employé
 Route::middleware(['auth:employee'])->prefix('espace-employee')->name('employee.')->group(function () {
    Route::get('/info', [EmployeeController::class, 'getInfoEmploiyeeById'])->name('info');
    Route::get('/espaceEmpShow/{employee}', [EmployeeController::class, 'showEmp'])->name('show');
    Route::post('/espaceEmp/{employee}/validate', [EmployeeController::class, 'validateCode'])->name('validate');
    Route::put('EspaceEmpUpdate/{employee}', [EmployeeController::class, 'EspaceEmpUpdate'])->name('EspaceEmpUpdate');
    Route::get('/contratsEmp/cdi/{id}', [EmployeeController::class, 'downloadCDIContractEmployeeAuth'])->name('contracts.cdi');

    Route::get('/contratsEmp/cdd/{id}', [EmployeeController::class, 'downloadCDDContractEmployeeAuth'])->name('contracts.cdd');

    Route::get('/paiements-details', [PaymentController::class, 'getInfoEmploiyeedetailsById'])->name('paiements.details');
    Route::get('/conges', [LeaveController::class, 'getInfoCongesEmploiyeeById'])->name('conges');
    Route::post('/conges/store', [LeaveController::class, 'storeCongesEmploiyeeById'])->name('conges.store');
    Route::post('/conges/annuler', [LeaveController::class, 'AnnulerCongesEmploiyeeById'])->name('conges.annuler');
    Route::get('/bultin', [BultinController::class, 'getInfoEmploiyeeBulletinById'])->name('bultin');
    Route::post('/imprimer-bultin', [BultinController::class, 'ImprimerBultinEmployeeAuth'])->name('bultin.imprimer');
    Route::get('/pointages', [AttendanceController::class, 'getInfoPointagesEmploiyeeById'])->name('pointages');

    

    Route::get('/Dashboard',function(){
        return view('pages.site.dashboard');
    })->name('dashboard');
});

    



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Leave.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    protected $fillable = [
        'employee_id', 'start_date', 'end_date', 'type', 'status',
    ];

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }
}

app/Http/Controllers/LeaveController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LeaveRequest;
use App\Models\Leave;
use App\Models\Employee;
use App\Models\User;
use App\Notifications\DemandeConge;
use App\Traits\LogsActivity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;

class LeaveController extends Controller
{

    use LogsActivity;

    function __construct()
{
$this->middleware('permission:list_conges|ajout_conges|modifier_conges|supprimer_conges', ['only' => ['index','store']]);
$this->middleware('permission:modifier_conges', ['only' => ['edit','update']]);
$this->middleware('permission:supprimer_conges', ['only' => ['destroy']]);
}

    public function index()
    {
        $leaves = Leave::with('employee')->get();
        $employees = Employee::all();
        return view('pages.leaves.index', compact('leaves', 'employees'));
    }

    public function store(LeaveRequest $request)
    {
        try {
            
            Leave::create([
                'employee_id' => $request->employee_id,
                'start_date' => $request->start_date,
                'end_date' => $request->end_date,
                'type' => $request->type,
                'status' => 'En Attente',
            ]);
            $dernierLeaveAjouter = Leave::latest()->first();
            $this->logActivity('Enregistrement', "Action sur conge id : ".$dernierLeaveAjouter->id);
            session()->flash('success', 'le conge a été ajouté avec succès!');
            return redirect()->route('leaves.index');
        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['error' => $e->getMessage()]);
        }
    }

    public function update(LeaveRequest $request)
    {
        try {

            $validated = $request->validated();
            $leave = Leave::findOrFail($request->id);
            $leave->update([
                'start_date' => $request->start_date,
                'end_date' => $request->end_date,
                'type' => $request->type,
                'status' => $request->status,
            ]);
            $this->logActivity('modification', "Action sur conge id : ".$request->id);
            session()->flash('success', 'le conge a été modifier avec succès!');
            return redirect()->route('leaves.index');
        } catch (\Exception $e) {
            return redirect()->back()->withErrors(['error' => $e->getMessage()]);
        }
    }

    public function show($id)
    {
        
        
        $leave = Leave::find($id);
         if(!$leave){
            session()->flash('info','le demande a ete annuler ou expire !');
            return redirect()->back();
         }

         return view('pages.leaves.details',compact('leave'));
    }

    public function redirectToLeave($notificationId)
{
    $notification = auth()->user()->unreadNotifications->find($notificationId);

    if ($notification) {
        $leaveId = $notification->data['id']; 
        $notification->markAsRead();
        return redirect()->route('leaves.show', $leaveId);
    }

    session()->flash('info', 'Cette notification a déjà été traitée ou n\'existe pas.');
    return redirect()->back();
}


    public function destroy(Request $request)
    {
        Leave::findOrFail($request->id)->delete();
        $this->logActivity('suppression', "Action sur conge id : ".$request->id);
        session()->flash('success', 'le conge a été supprimer avec succès!');
        return redirect()->route('leaves.index');
    }

    public function MarkAsRead_all(Request $request)
    {
        $userUnreadNotification = auth()->user()->unreadNotifications;
        if($userUnreadNotification){
            $userUnreadNotification->markAsRead();
            return back();

        }

    }

    // ------------- information employee authentifier -------------//
    public function getInfoCongesEmploiyeeById()
{
    $employee = auth()->guard('employee')->user();
    $leaves = Leave::with('employee')->where('employee_id', $employee->id)->get();

    return view('pages.site.leaves.index', compact('leaves','employee'));
}

public function storeCongesEmploiyeeById(Request $request)
{
    try {    
        Leave::create([
            'employee_id' => $request->employee_id,
            'start_date' => $request->start_date,
            'end_date' => $request->end_date,
            'type' => $request->type,
            'status' => 'En Attente',
        ]);

        $user = User::get();
        $conge = Leave::latest()->first();
         Notification::send($user,new DemandeConge($conge));
         session()->flash('success', 'votre demande de conge a ete envoiyer avec succès!');
        return redirect()->route('employee.conges');
    } catch (\Exception $e) {
        return redirect()->back()->withErrors(['error' => $e->getMessage()]);
    } 
}
  public function AnnulerCongesEmploiyeeById(Request $request)
  {
    Leave::findOrFail($request->id)->delete();
    session()->flash('success', 'votre demande conge a ete annuler avec succès!');
    return redirect()->route('employee.conges');

  }
}

resources/views/pages/site/leaves/index.blade.php
@extends('layouts.site.master')
@section('css')
@endsection
@section('title')
    {{ __('Congés') }}
@endsection
@section('content-header')
    <div class="widget-header p-2">
        <div class="row">
            <div class="col-xl-9 col-md-9 col-sm-9 col-9">
                <div class="mt-2">
                    <a href="#">{{ __('Home') }}</a>/<a href="#">{{ __('Congés') }}</a>
                </div>
            </div>
            <div class="col-xl-3 col-md-3 col-sm-3 col-3 text-right">
                <button type="button" class="btn btn-success btn-sm" data-toggle="modal" data-target="#addLeaveModal">
                    <i class="fas fa-add"></i>
                    {{ __('Demande Congé') }}
                </button>
            </div>
        </div>
    </div>
@endsection
@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>{{ __('Employé') }}</th>
                <th>{{ __('Date de début') }}</th>
                <th>{{ __('Date de fin') }}</th>
                <th>{{ __('Type') }}</th>
                <th>{{ __('Statut') }}</th>
                <th class="text-center">{{ __('Opérations') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($leaves as $leave)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $leave->employee->first_name }} {{ $leave->employee->last_name }}</td>
                    <td>{{ $leave->start_date }}</td>
                    <td>{{ $leave->end_date }}</td>
                    <td>{{ $leave->type }}</td>
                    <td>{{ $leave->status }}</td>
                    <td class="text-center">
                        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteLeaveModal{{ $leave->id }}">
                            <i class="fas fa-times"></i>

                            {{ __('Annuler') }}</button>
                    </td>
                </tr>

                <!-- Edit Modal -->
                <div class="modal fade" id="editLeaveModal{{ $leave->id }}" tabindex="-1" role="dialog" aria-labelledby="editLeaveModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="editLeaveModalLabel">{{ __('Modifier Congé') }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{{ route('leaves.update',$leave->id) }}" method="post">
                                    @method('patch')
                                    @csrf
                                    <input type="hidden" name="id" value="{{ $leave->id }}">
                                    <input type="hidden" name="employee_id" value="{{ $employee->id }}">
                                    
                                    <div class="form-group">
                                        <label for="start_date">{{ __('Date de début') }}</label>
                                        <input type="date" name="start_date" class="form-control" value="{{ $leave->start_date }}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="end_date">{{ __('Date de fin') }}</label>
                                        <input type="date" name="end_date" class="form-control" value="{{ $leave->end_date }}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="type">{{ __('Type') }}</label>
                                        <input type="text" name="type" class="form-control" value="{{ $leave->type }}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="status">{{ __('Statut') }}</label>
                                        <select name="status" class="form-control">
                                            <option value="En Attente" {{ $leave->status == 'En Attente' ? 'selected' : '' }}>{{ __('En Attente') }}</option>
                                            <option value="Approuvé" {{ $leave->status == 'Approuvé' ? 'selected' : '' }}>{{ __('Approuvé') }}</option>
                                            <option value="Refusé" {{ $leave->status == 'Refusé' ? 'selected' : '' }}>{{ __('Refusé') }}</option>
                                        </select>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Annuler') }}</button>
                                        <button type="submit" class="btn btn-success">{{ __('Modifier') }}</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Delete Modal -->
                <div class="modal fade" id="deleteLeaveModal{{ $leave->id }}" tabindex="-1" role="dialog" aria-labelledby="deleteLeaveModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="deleteLeaveModalLabel">{{ __('Annuler Congé') }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form action="{{ route('employee.conges.annuler',$leave->id) }}" method="post">
                                    @csrf  
                                    {{ __('Êtes-vous sûr de vouloir ANNULER ce congé?') }}
                                    <input type="hidden" name="id" value="{{ $leave->id }}">
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-times"></i>
                                        </button>
                                        <button type="submit" class="btn btn-danger"><i class="fas fa-check"></i>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </tbody>
    </table>

    <!-- Add Modal -->
    <div class="modal fade" id="addLeaveModal" tabindex="-1" role="dialog" aria-labelledby="addLeaveModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addLeaveModalLabel">{{ __('Demande Congé') }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('employee.conges.store') }}" method="post">
                        @csrf
                        <div class="form-group">
                            <label for="employee_id">{{ __('Employé') }}</label>
                            <input type="hidden" name="employee_id" value="{{ $employee->id }}">
                        </div>
                        <div class="form-group">
                            <label for="start_date">{{ __('Date de début') }}</label>
                            <input type="date" name="start_date" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="end_date">{{ __('Date de fin') }}</label>
                            <input type="date" name="end_date" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="type">{{ __('Type') }}</label>
                            <input type="text" name="type" class="form-control" required>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fas fa-ban"></i>
                                {{ __('Annuler') }}</button>
                            <button type="submit" class="btn btn-success"><i class="fas fa-save"></i>
                                {{ __('Enregistrer') }}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('js')
    <script>
        $(document).ready(function() {
            $('table').DataTable({
                "dom": "<'dt--top-section'<'row'<'col-12 col-sm-6 d-flex justify-content-sm-start justify-content-center'l><'col-12 col-sm-6 d-flex justify-content-sm-end justify-content-center mt-sm-0 mt-3'f>>>" +
                    "<'table-responsive'tr>" +
                    "<'dt--bottom-section d-sm-flex justify-content-sm-between text-center'<'dt--pages-count  mb-sm-0 mb-3'i><'dt--pagination'p>>",
                "oLanguage": {
                    "oPaginate": {
                        "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>',
                        "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>'
                    },
                    "sInfo": "Showing page _PAGE_ of _PAGES_",
                    "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
                    "sSearchPlaceholder": "Search...",
                    "sLengthMenu": "Results :  _MENU_",
                },
                "stripeClasses": [],
                "lengthMenu": [7, 10, 20, 50],
                "pageLength": 7,
                drawCallback: function() {
                    $('.dataTables_wrapper table').removeClass('table-striped');
                }
            });
        });
    </script>
@endsection