routes/web.php
<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\Auth\UnifiedLoginController;
use App\Http\Controllers\BultinController;
use App\Http\Controllers\Departments\DepartmentController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LeaveController;
use App\Http\Controllers\LettreController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\Positions\PositionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StatistiqueController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;



Route::get('/', function () {
    return view('auth.login');
});


Route::middleware(['web.auth'])->prefix('espace-admin')->group(function () {
    // Departments 
    Route::resource('departments', DepartmentController::class);

    // Positions
    Route::resource('positions', PositionController::class);
    Route::get('/positions-by-department/{department}', [PositionController::class, 'getByDepartment'])->name('positions.by.department');
    Route::get('/positions-department/{department}', [PositionController::class, 'getPositionByDepartment'])->name('positionsBydepartment');
    // Employees
    Route::resource('employees', EmployeeController::class);
    Route::get('/contrats/cdi/{id}', [EmployeeController::class, 'downloadCDIContract'])->name('contracts.cdi');
    Route::get('/contrats/cdd/{id}', [EmployeeController::class, 'downloadCDDContract'])->name('contracts.cdd');
    

    // Congés
    Route::resource('leaves', LeaveController::class);
    Route::get('notifications/{id}/read', [LeaveController::class, 'redirectToLeave'])->name('notification.read');
    Route::get('MarkAsRead_all',[LeaveController::class,'MarkAsRead_all'])->name('MarkAsRead_all');
    // Présences
    Route::resource('attendances', AttendanceController::class);
    Route::get('list_attendances', [AttendanceController::class, 'list'])->name('attendances.list');
    Route::get('edit_attendance', [AttendanceController::class,'editAttendance'])->name('attendances.editAttendance');
    Route::get('/pointages/download-pdf', [AttendanceController::class, 'downloadPDF'])->name('attendances.downloadPDF');



    // Paiements
    Route::resource('payments', PaymentController::class);
    Route::get('Details', [PaymentController::class, 'details'])->name('payments.Details');
    Route::get('/paiements/download-pdf', [PaymentController::class, 'downloadPDF'])->name('payments.downloadPDF');
    Route::post('paiements/mass-store', [PaymentController::class, 'massStore'])->name('payments.mass_store');



    // Bulletins
    Route::get('/GenererBulltin', [BultinController::class, 'index'])->name('bulletin.generate');
    Route::post('/showBultinEmploye', [BultinController::class, 'showBulletin'])->name('bulltin.show');
    Route::post('/showBultinPatron', [BultinController::class, 'showBultinPatron'])->name('bulltin.showPatron');

    // Factures
    Route::resource('invoices', InvoiceController::class);
    Route::get('/invoice/{id}/print', [InvoiceController::class, 'print'])->name('invoices.print');
    Route::get('/factures/{invoice}/pdf', [InvoiceController::class, 'downloadInvoice'])->name('invoices.download');


    // Lettres
    Route::get('/lettre/create', [LettreController::class, 'createLettre'])->name('lettre.create');
    Route::get('/lettre/imprimer', [LettreController::class, 'imprimer'])->name('lettre.imprimer');

    Route::get('/Statistique',[StatistiqueController::class,'index'])->name('dashboard.statistique');

    Route::get('/test',function(){
        return view('pages.TestLivewire');
    });
});




// Auth::routes();

Route::get('login', [UnifiedLoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [UnifiedLoginController::class, 'login'])->name('login');
Route::post('logout', [UnifiedLoginController::class, 'logout'])->name('logout');

// Routes pour les utilisateurs généraux (users)
Route::prefix('user')->group(function () {
    Route::get('password/reset', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request');
    Route::post('password/email', [ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email');
    Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
    Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');
});

Route::group(['middleware' => ['auth']],function(){

    Route::resource('roles',RoleController::class);
    Route::resource('users',UserController::class);

});


 // Groupe de routes pour l'espace employé
 Route::middleware(['auth:employee'])->prefix('espace-employee')->name('employee.')->group(function () {
    Route::get('/info', [EmployeeController::class, 'getInfoEmploiyeeById'])->name('info');
    Route::get('/espaceEmpShow/{employee}', [EmployeeController::class, 'showEmp'])->name('show');
    Route::post('/espaceEmp/{employee}/validate', [EmployeeController::class, 'validateCode'])->name('validate');
    Route::put('EspaceEmpUpdate/{employee}', [EmployeeController::class, 'EspaceEmpUpdate'])->name('EspaceEmpUpdate');
    Route::get('/contratsEmp/cdi/{id}', [EmployeeController::class, 'downloadCDIContractEmployeeAuth'])->name('contracts.cdi');

    Route::get('/contratsEmp/cdd/{id}', [EmployeeController::class, 'downloadCDDContractEmployeeAuth'])->name('contracts.cdd');

    Route::get('/paiements-details', [PaymentController::class, 'getInfoEmploiyeedetailsById'])->name('paiements.details');
    Route::get('/conges', [LeaveController::class, 'getInfoCongesEmploiyeeById'])->name('conges');
    Route::post('/conges/store', [LeaveController::class, 'storeCongesEmploiyeeById'])->name('conges.store');
    Route::post('/conges/annuler', [LeaveController::class, 'AnnulerCongesEmploiyeeById'])->name('conges.annuler');
    Route::get('/bultin', [BultinController::class, 'getInfoEmploiyeeBulletinById'])->name('bultin');
    Route::post('/imprimer-bultin', [BultinController::class, 'ImprimerBultinEmployeeAuth'])->name('bultin.imprimer');
    Route::get('/pointages', [AttendanceController::class, 'getInfoPointagesEmploiyeeById'])->name('pointages');

    

    Route::get('/Dashboard',function(){
        return view('pages.site.dashboard');
    })->name('dashboard');
});

    



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/pages/site/employes/contratPdfCDD.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contrat CDD</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        .container {
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .content {
            text-align: justify;
        }
        .signature {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
        }
        .signature div {
            width: 48%; /* Permet d'équilibrer l'espace entre les deux signatures */
        }
        .employer-signature {
            display: flex;
            align-items: center; /* Centre verticalement l'image et le texte */
            gap: 10px; /* Espacement entre l'image et le texte */
        }
        .employer-signature img {
            width: 100px; /* Taille de l'image, ajustable */
            height: auto;
        }
        .employee-signature {
            text-align: left;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Contrat de Travail - CDD</h1>
        </div>
        <div class="content">
            <p>
                Entre les soussignés : <br>
                <strong>L'Entreprise :</strong> {{ $company_name }}, représentée par {{ $employer_name }}.<br>
                Et <br>
                <strong>L'Employé :</strong> {{ $employee_name }}.
            </p>
            <p>
                Il est convenu ce qui suit :
            </p>
            <p>
                <strong>1. Nature du contrat :</strong><br>
                Ce contrat est conclu pour une durée déterminée de <strong>{{ $duration }} ans</strong>.
            </p>
            <p>
                <strong>2. Poste et responsabilités :</strong><br>
                L'employé sera affecté au poste de <strong>{{ $position }}</strong> 
                dans le département <strong>{{ $department }}</strong>.
            </p>
            <p>
                <strong>3. Salaire :</strong><br>
                L'employé percevra un salaire mensuel de <strong>{{ $salary }} MRU</strong>.
            </p>
            <p>
                <strong>4. Durée hebdomadaire de travail :</strong><br>
                La durée de travail hebdomadaire est fixée à 40 heures.
            </p>
            <p>
                <strong>5. Date d'entrée en fonction :</strong><br>
                L'employé prendra ses fonctions le <strong>{{ $start_date }}</strong>.
            </p>
        </div>
        <div class="signature">
            <div class="employer-signature">
                <div>
                    <p>Signature de l'Employeur : 
                        <img src="data:image/png;base64,<?php echo base64_encode(file_get_contents(public_path('images/EGTT_CACHE.png'))); ?>">
                    </p>
                    <p>________________________</p>
                </div>
            </div>
            <div class="employee-signature">
                <p>Signature de l'Employé :</p>
                <p>________________________</p>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/pages/site/employes/contratPdfCDI.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contrat CDI</title>
  <style>
    body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
        }
        .container {
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .content {
            text-align: justify;
        }
        .signature {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
        }
        .signature div {
            width: 48%; /* Permet d'équilibrer l'espace entre les deux signatures */
        }
        .employer-signature {
            display: flex;
            align-items: center; /* Centre verticalement l'image et le texte */
            gap: 10px; /* Espacement entre l'image et le texte */
        }
        .employer-signature img {
            width: 100px; /* Taille de l'image, ajustable */
            height: auto;
        }
        .employee-signature {
            text-align: left;
        }
    </style>
  </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Contrat de Travail - CDI</h1>
        </div>
        <div class="content">
            <p>
                Entre les soussignés : <br>
                <strong>L'Entreprise :</strong> {{ $company_name }}, représentée par {{ $employer_name }}.<br>
                Et <br>
                <strong>L'Employé :</strong> {{ $employee_name }}.
            </p>
            <p>
                Il est convenu ce qui suit :
            </p>
            <p>
                <strong>1. Nature du contrat :</strong><br>
                Ce contrat est conclu pour une durée indéterminée.
            </p>
            <p>
                <strong>2. Poste et responsabilités :</strong><br>
                L'employé sera affecté au poste de <strong>{{ $position }}</strong> 
                dans le département <strong>{{ $department }}</strong>.
            </p>
            <p>
                <strong>3. Salaire :</strong><br>
                L'employé percevra un salaire mensuel de <strong>{{ $salary }} MRU</strong>.
            </p>
            <p>
                <strong>4. Durée hebdomadaire de travail :</strong><br>
                La durée de travail hebdomadaire est fixée à 40 heures.
            </p>
            <p>
                <strong>5. Date d'entrée en fonction :</strong><br>
                L'employé prendra ses fonctions le <strong>{{ $start_date }}</strong>.
            </p>
        </div>



        <div class="signature">
            <div class="employer-signature">
            <div>
                <p>Signature de l'Employeur :</p>
                <img src="data:image/png;base64,<?php echo base64_encode(file_get_contents(public_path('images/EGTT_CACHE.png'))); ?>">
                <p>________________________</p>
            </div>
            </div>
            <div class="employee-signature">
                <p>Signature de l'Employé :</p>
                <p>________________________</p>
            </div>
        </div>
    </div>
</body>
</html>

resources/views/pages/site/employes/index.blade.php
@extends('layouts.site.master')

@section('css')
<style>
    .section-title {
        font-size: 1.5rem;
        font-weight: bold;
        text-align: center;
        margin-bottom: 20px;
    }
    .info-section {
        margin-bottom: 30px;
    }
    .info-item {
        display: flex;
        justify-content: space-between;
        margin-bottom: 10px;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        background-color: #f9f9f9;
    }
    .info-item strong {
        margin-right: 10px;
    }

    .photo-section {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 20px;
}

.profile-photo {
    width: 150px;
    height: 150px;
    border-radius: 50%;
    object-fit: cover;
    border: 3px solid #ddd;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
}

.default-photo {
    width: 150px;
    height: 150px;
    border-radius: 50%;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #f0f0f0;
    color: #aaa;
    font-size: 14px;
    border: 3px solid #ddd;
    box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.1);
}

</style>
@endsection

@section('title')
    {{ __('Détails Employé') }}
@endsection

@section('content-header')
    <div class="widget-header p-2">
        <div class="row">
            <div class="col-9 mt-2">
                <a href="#">{{ __('Accueil') }}</a> / <a href="#">{{ __('Détails Employé') }}</a>
            </div>
            <div class="col-3 text-right">
                <a href="{{ route('employees.index') }}" class="btn btn-info btn-sm">
                    <i class="fas fa-arrow-left"></i>
    {{ __('Retour') }}
                </a>
                <!-- Bouton Modifier -->
                <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#editModal">
                   <i class="fas fa-edit"></i> {{ __('Modifier') }}
                </button>
            </div>
        </div>
    </div>
@endsection

@section('content')
<div class="container">
    
    <!-- Photo de Profil -->
    <div class="photo-section text-center mb-4">
        @if ($employee->photo)
        <img src="{{ asset('storage/' . $employee->photo) }}" alt="Photo de Profil" class="profile-photo">
        @else
            <div class="default-photo">
                <span>{{ __('Aucune photo disponible') }}</span>
            </div>
        @endif
    </div>

    <!-- Informations Personnelles -->
    <div class="info-section">
        <div class="section-title">{{ __('Informations Personnelles') }}</div>
        <div class="info-item">
            <strong>{{ __('Prénom :') }}</strong>
            <span>{{ $employee->first_name }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Nom :') }}</strong>
            <span>{{ $employee->last_name }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Date de naissance :') }}</strong>
            <span>{{ \Carbon\Carbon::parse($employee->date_of_birth)->format('d/m/Y') }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Adresse :') }}</strong>
            <span>{{ $employee->address }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Téléphone :') }}</strong>
            <span><a href="tel:{{ $employee->phone }}">{{ $employee->phone }}</a></span>
        </div>
        <div class="info-item">
            <strong>{{ __('Email :') }}</strong>
            <span><a href="mailto:{{ $employee->email }}">{{ $employee->email }}</a></span>
        </div>
    </div>

    <!-- Informations Professionnelles -->
    <div class="info-section">
        <div class="section-title">{{ __('Informations Professionnelles') }}</div>
        <div class="info-item">
            <strong>{{ __('NNI :') }}</strong>
            <span>{{ $employee->nni }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Matricule :') }}</strong>
            <span>{{ $employee->matricule }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Position :') }}</strong>
            <span>{{ $employee->position->title }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Département :') }}</strong>
            <span>{{ $employee->position->department->name }}</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Salaire :') }}</strong>
            <span>{{ $employee->position->base_salary }} MRU</span>
        </div>
        <div class="info-item">
            <strong>{{ __('Date d\'embauche :') }}</strong>
            <span>{{ \Carbon\Carbon::parse($employee->date_of_hire)->format('d/m/Y') }}</span>
        </div>

        <!-- Type de contrat -->
        <div class="info-item">
            <strong>{{ __('Type de contrat :') }}</strong>
            <span>{{ $employee->contract_type }}</span>
        </div>

        <!-- Durée du contrat (affiché uniquement pour CDD) -->
        @if ($employee->contract_type === 'CDD')
            <div class="info-item">
                <strong>{{ __('Durée du contrat :') }}</strong>
                <span>{{ $employee->contract_duration }} ans</span>
            </div>


        @endif
    </div>
    <!-- Télécharger le contrat -->
    <div class="info-section text-center">
        @if($employee->contract_type === 'CDD')
            <a href="{{ route('employee.contracts.cdd', $employee->id) }}" class="btn btn-primary" title="Télécharger Contrat CDD">
                <i class="fas fa-download"></i> Telecharger Votre Contrat CDD en PDF
            </a>
        @else
            <a href="{{ route('employee.contracts.cdi', $employee->id) }}" class="btn btn-primary" title="Télécharger Contrat CDI">
                <i class="fas fa-download"></i>Telecharger Votre Contrat CDI en PDF
            </a>
        @endif
    </div>

    
</div>

<!-- Modal Modifier -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">{{ __('Modifier les Informations') }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('employee.EspaceEmpUpdate', $employee->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="modal-body">
                    <!-- Champ pour la photo -->
                    <div class="form-group">
                        <label for="photo">{{ __('Photo de Profil') }}</label>
                        <div class="custom-file">
                            <input type="file" name="photo" id="photo" class="custom-file-input" onchange="previewImage(event)">
                            <label class="custom-file-label" for="photo">{{ __('Choisir une photo') }}</label>
                        </div>
                        <div id="photoPreview" class="mt-3">
                            @if ($employee->photo)
                                <img src="{{ asset('storage/' . $employee->photo) }}" alt="Photo" class="img-thumbnail" style="max-width: 150px; height: auto;">
                            @else
                                <img id="previewImage" src="#" alt="Aucune image" class="img-thumbnail" style="max-width: 150px; height: auto; display: none;">
                            @endif
                        </div>
                    </div>

                    <!-- Champ pour le téléphone -->
                    <div class="form-group">
                        <label for="phone">{{ __('Téléphone') }}</label>
                        <input type="text" name="phone" id="phone" class="form-control" value="{{ $employee->phone }}" required>
                    </div>

                    <!-- Champ pour l'adresse -->
                    <div class="form-group">
                        <label for="address">{{ __('Adresse') }}</label>
                        <input type="text" name="address" id="address" class="form-control" value="{{ $employee->address }}" required>
                    </div>

                    <!-- Champ pour le mot de passe -->
                    <div class="form-group">
                        <label for="password">{{ __('Mot de passe') }}</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="{{ __('Nouveau mot de passe') }}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Fermer') }}</button>
                    <button type="submit" class="btn btn-primary">{{ __('Sauvegarder') }}</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('js')
<!-- Script pour prévisualisation d'image -->
<script>
    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.getElementById('previewImage');
            output.style.display = 'block';
            output.src = reader.result;
        };
        reader.readAsDataURL(event.target.files[0]);
    }
</script>
@endsection

resources/views/pages/site/employes/show.blade.php
@extends('layouts.site.master')

@section('title')
    {{ __('Validation de Modifications') }}
@endsection

@section('content-header')
    <div class="widget-header p-2">
        <div class="row">
            <div class="col-9 mt-2">
                <a href="#">{{ __('Accueil') }}</a> / <a href="#">{{ __('Validation de Modifications') }}</a>
            </div>
            <div class="col-3 text-right">
                <a href="{{ route('employee.info') }}" class="btn btn-secondary btn-sm">
                    {{ __('Retour') }}
                </a>
            </div>
        </div>
    </div>
@endsection

@section('content')
<div class="container">
    <h3 class="text-center">{{ __('Validation de vos Modifications') }}</h3>

    @if(session('message'))
        <div class="alert alert-info">
            {{ session('message') }}
        </div>
    @endif


 

    <form action="{{ route('employee.validate', $employee->id) }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="validation_code">{{ __('Code de Validation') }}</label>
            <input type="text" name="validation_code" id="validation_code" class="form-control" placeholder="Entrez le code reçu" required>
        </div>

        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary">{{ __('Valider les Modifications') }}</button>
        </div>
    </form>
</div>
@endsection